"""Report templates for different output formats.

Provides customizable templates for Markdown, HTML, and other formats.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Any, Optional, List
from string import Template

from shakka.reports.models import Report, Finding, Severity


# =============================================================================
# Default Templates
# =============================================================================

DEFAULT_MARKDOWN_TEMPLATE = '''# ${title}

**Classification:** ${classification}  
**Version:** ${version}  
**Date:** ${date}

---

## Document Information

| Field | Value |
|-------|-------|
| Client | ${client} |
| Assessor | ${assessor} |
| Assessment Type | ${assessment_type} |
| Assessment Period | ${start_date} - ${end_date} |

---

## Executive Summary

${executive_summary}

### Risk Overview

| Severity | Count |
|----------|-------|
| Critical | ${critical_count} |
| High | ${high_count} |
| Medium | ${medium_count} |
| Low | ${low_count} |
| Informational | ${info_count} |
| **Total** | **${total_findings}** |

**Overall Risk Score:** ${risk_score}/100

---

## Scope

${scope}

---

## Methodology

${methodology}

---

## Findings

${findings_section}

---

## Remediation Summary

${remediation_summary}

---

*Report generated by ShakkaShell on ${generated_at}*
'''

DEFAULT_FINDING_TEMPLATE = '''### ${finding_number}. ${title}

**Severity:** ${severity_badge}  
**CVSS Score:** ${cvss_score}  
**Affected Asset:** ${affected_asset}

#### Description

${description}

${cve_section}

#### Evidence

${evidence_section}

#### Remediation

${remediation}

#### References

${references}

---
'''

DEFAULT_HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        :root {
            --critical-color: #DC143C;
            --high-color: #FF4500;
            --medium-color: #FFA500;
            --low-color: #FFD700;
            --info-color: #1E90FF;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        h1, h2, h3 { color: #2c3e50; }
        .header {
            border-bottom: 3px solid #2c3e50;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .classification {
            background: #ffcc00;
            padding: 5px 15px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th { background: #f5f5f5; }
        .severity-badge {
            padding: 4px 12px;
            border-radius: 4px;
            color: white;
            font-weight: bold;
            display: inline-block;
        }
        .severity-critical { background: var(--critical-color); }
        .severity-high { background: var(--high-color); }
        .severity-medium { background: var(--medium-color); color: #333; }
        .severity-low { background: var(--low-color); color: #333; }
        .severity-info { background: var(--info-color); }
        .finding {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
            background: #fafafa;
        }
        .finding h3 {
            margin-top: 0;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .evidence {
            background: #f5f5f5;
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 15px;
            margin: 10px 0;
        }
        .evidence pre {
            background: #1e1e1e;
            color: #d4d4d4;
            padding: 15px;
            border-radius: 4px;
            overflow-x: auto;
        }
        .risk-score {
            font-size: 2em;
            font-weight: bold;
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .risk-high { background: #ffe6e6; color: #cc0000; }
        .risk-medium { background: #fff3cd; color: #856404; }
        .risk-low { background: #d4edda; color: #155724; }
        .toc { background: #f5f5f5; padding: 20px; border-radius: 8px; }
        .toc ul { list-style-type: none; padding-left: 20px; }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="classification">${classification}</div>
    
    <div class="header">
        <h1>${title}</h1>
        <p><strong>Version:</strong> ${version} | <strong>Date:</strong> ${date}</p>
    </div>
    
    <h2>Document Information</h2>
    <table>
        <tr><th>Client</th><td>${client}</td></tr>
        <tr><th>Assessor</th><td>${assessor}</td></tr>
        <tr><th>Assessment Type</th><td>${assessment_type}</td></tr>
        <tr><th>Assessment Period</th><td>${start_date} - ${end_date}</td></tr>
    </table>
    
    <h2>Executive Summary</h2>
    <p>${executive_summary}</p>
    
    <h3>Risk Overview</h3>
    <table>
        <tr>
            <th>Severity</th>
            <th>Count</th>
        </tr>
        <tr>
            <td><span class="severity-badge severity-critical">Critical</span></td>
            <td>${critical_count}</td>
        </tr>
        <tr>
            <td><span class="severity-badge severity-high">High</span></td>
            <td>${high_count}</td>
        </tr>
        <tr>
            <td><span class="severity-badge severity-medium">Medium</span></td>
            <td>${medium_count}</td>
        </tr>
        <tr>
            <td><span class="severity-badge severity-low">Low</span></td>
            <td>${low_count}</td>
        </tr>
        <tr>
            <td><span class="severity-badge severity-info">Informational</span></td>
            <td>${info_count}</td>
        </tr>
        <tr>
            <th>Total</th>
            <th>${total_findings}</th>
        </tr>
    </table>
    
    <div class="risk-score ${risk_class}">
        Overall Risk Score: ${risk_score}/100
    </div>
    
    <h2>Scope</h2>
    ${scope}
    
    <h2>Methodology</h2>
    <p>${methodology}</p>
    
    <h2>Findings</h2>
    ${findings_section}
    
    <h2>Remediation Summary</h2>
    ${remediation_summary}
    
    <div class="footer">
        <p>Report generated by ShakkaShell on ${generated_at}</p>
    </div>
</body>
</html>
'''

DEFAULT_HTML_FINDING_TEMPLATE = '''
<div class="finding">
    <h3>${finding_number}. ${title}</h3>
    <p>
        <span class="severity-badge severity-${severity_lower}">${severity}</span>
        <strong>CVSS:</strong> ${cvss_score}
    </p>
    <p><strong>Affected Asset:</strong> ${affected_asset}</p>
    
    <h4>Description</h4>
    <p>${description}</p>
    
    ${cve_section}
    
    <h4>Evidence</h4>
    ${evidence_section}
    
    <h4>Remediation</h4>
    <p>${remediation}</p>
    
    <h4>References</h4>
    ${references}
</div>
'''


@dataclass
class ReportTemplate:
    """A customizable report template."""
    
    name: str
    description: str = ""
    report_template: str = DEFAULT_MARKDOWN_TEMPLATE
    finding_template: str = DEFAULT_FINDING_TEMPLATE
    format_type: str = "markdown"  # markdown, html
    custom_styles: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "name": self.name,
            "description": self.description,
            "report_template": self.report_template,
            "finding_template": self.finding_template,
            "format_type": self.format_type,
            "custom_styles": self.custom_styles,
            "metadata": self.metadata,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ReportTemplate":
        """Create from dictionary."""
        return cls(
            name=data["name"],
            description=data.get("description", ""),
            report_template=data.get("report_template", DEFAULT_MARKDOWN_TEMPLATE),
            finding_template=data.get("finding_template", DEFAULT_FINDING_TEMPLATE),
            format_type=data.get("format_type", "markdown"),
            custom_styles=data.get("custom_styles", ""),
            metadata=data.get("metadata", {}),
        )


class TemplateRegistry:
    """Registry of available report templates."""
    
    def __init__(self):
        """Initialize with default templates."""
        self._templates: Dict[str, ReportTemplate] = {}
        self._register_defaults()
    
    def _register_defaults(self):
        """Register default templates."""
        # Default Markdown template
        self.register(ReportTemplate(
            name="default",
            description="Standard penetration testing report template",
            report_template=DEFAULT_MARKDOWN_TEMPLATE,
            finding_template=DEFAULT_FINDING_TEMPLATE,
            format_type="markdown",
        ))
        
        # HTML template
        self.register(ReportTemplate(
            name="html",
            description="Styled HTML report template",
            report_template=DEFAULT_HTML_TEMPLATE,
            finding_template=DEFAULT_HTML_FINDING_TEMPLATE,
            format_type="html",
        ))
        
        # Executive summary focused
        self.register(ReportTemplate(
            name="executive",
            description="Executive-focused summary report",
            report_template=self._get_executive_template(),
            finding_template=self._get_executive_finding_template(),
            format_type="markdown",
        ))
        
        # Technical detailed
        self.register(ReportTemplate(
            name="technical",
            description="Detailed technical report with full evidence",
            report_template=DEFAULT_MARKDOWN_TEMPLATE,
            finding_template=self._get_technical_finding_template(),
            format_type="markdown",
        ))
    
    def _get_executive_template(self) -> str:
        """Get executive summary focused template."""
        return '''# ${title}

**Classification:** ${classification}

---

## Executive Summary

${executive_summary}

### Key Statistics

- **Total Findings:** ${total_findings}
- **Critical Issues:** ${critical_count}
- **High Severity Issues:** ${high_count}
- **Overall Risk Score:** ${risk_score}/100

### Immediate Actions Required

${critical_findings_summary}

---

## Assessment Overview

| Field | Value |
|-------|-------|
| Client | ${client} |
| Assessment Period | ${start_date} - ${end_date} |
| Scope | ${scope_summary} |

---

## Findings Summary

${findings_summary_table}

---

*Report generated by ShakkaShell on ${generated_at}*
'''
    
    def _get_executive_finding_template(self) -> str:
        """Get executive finding template (minimal detail)."""
        return '''| ${finding_number} | ${title} | ${severity} | ${affected_asset} |
'''
    
    def _get_technical_finding_template(self) -> str:
        """Get detailed technical finding template."""
        return '''### ${finding_number}. ${title}

**Severity:** ${severity_badge}  
**CVSS Score:** ${cvss_score} (${cvss_vector})  
**Affected Asset:** ${affected_asset}

#### Vulnerability Details

${description}

#### Technical Analysis

**CVE IDs:** ${cve_ids}  
**CWE IDs:** ${cwe_ids}

#### Proof of Concept

${evidence_section}

#### Impact Assessment

This vulnerability could allow an attacker to:
${impact_analysis}

#### Remediation

${remediation}

**Priority:** ${remediation_priority}

#### References

${references}

#### Timeline

- **Discovered:** ${discovered_at}
- **Reported:** ${reported_at}

---
'''
    
    def register(self, template: ReportTemplate):
        """Register a template."""
        self._templates[template.name] = template
    
    def get(self, name: str) -> Optional[ReportTemplate]:
        """Get a template by name."""
        return self._templates.get(name)
    
    def get_all(self) -> List[ReportTemplate]:
        """Get all registered templates."""
        return list(self._templates.values())
    
    def list_names(self) -> List[str]:
        """List all template names."""
        return list(self._templates.keys())
    
    def remove(self, name: str) -> bool:
        """Remove a template."""
        if name in self._templates:
            del self._templates[name]
            return True
        return False


class TemplateRenderer:
    """Renders reports using templates."""
    
    def __init__(self, template: Optional[ReportTemplate] = None):
        """Initialize renderer with optional template."""
        self.template = template or ReportTemplate(
            name="default",
            report_template=DEFAULT_MARKDOWN_TEMPLATE,
            finding_template=DEFAULT_FINDING_TEMPLATE,
        )
    
    def render(self, report: Report) -> str:
        """Render a report using the template.
        
        Args:
            report: Report to render
            
        Returns:
            Rendered report string
        """
        # Build context for template substitution
        context = self._build_report_context(report)
        
        # Render findings section
        findings_section = self._render_findings(report)
        context["findings_section"] = findings_section
        
        # Render remediation summary
        context["remediation_summary"] = self._render_remediation_summary(report)
        
        # Use safe substitution
        template = Template(self.template.report_template)
        return template.safe_substitute(context)
    
    def _build_report_context(self, report: Report) -> Dict[str, str]:
        """Build template context from report."""
        meta = report.metadata
        now = datetime.now()
        
        # Format scope as bullet list
        scope_list = "\n".join(f"- {s}" for s in meta.scope) if meta.scope else "Not specified"
        scope_summary = ", ".join(meta.scope[:3]) + ("..." if len(meta.scope) > 3 else "")
        
        # Risk class for HTML
        risk_class = "risk-high" if report.risk_score >= 70 else (
            "risk-medium" if report.risk_score >= 40 else "risk-low"
        )
        
        return {
            "title": meta.title,
            "classification": meta.classification,
            "version": meta.version,
            "date": now.strftime("%Y-%m-%d"),
            "client": meta.client or "Not specified",
            "assessor": meta.assessor or "Not specified",
            "assessment_type": meta.assessment_type,
            "start_date": meta.start_date.strftime("%Y-%m-%d") if meta.start_date else "N/A",
            "end_date": meta.end_date.strftime("%Y-%m-%d") if meta.end_date else "N/A",
            "executive_summary": meta.executive_summary or "No executive summary provided.",
            "methodology": meta.methodology or "Standard penetration testing methodology.",
            "scope": scope_list,
            "scope_summary": scope_summary or "Not specified",
            "critical_count": str(report.critical_count),
            "high_count": str(report.high_count),
            "medium_count": str(report.medium_count),
            "low_count": str(report.low_count),
            "info_count": str(report.info_count),
            "total_findings": str(report.total_findings),
            "risk_score": f"{report.risk_score:.0f}",
            "risk_class": risk_class,
            "generated_at": now.strftime("%Y-%m-%d %H:%M:%S"),
            "critical_findings_summary": self._get_critical_summary(report),
            "findings_summary_table": self._get_findings_table(report),
        }
    
    def _render_findings(self, report: Report) -> str:
        """Render all findings."""
        if not report.findings:
            return "*No findings to report.*"
        
        sections = []
        for i, finding in enumerate(report.sorted_findings, 1):
            context = self._build_finding_context(finding, i)
            template = Template(self.template.finding_template)
            sections.append(template.safe_substitute(context))
        
        return "\n".join(sections)
    
    def _build_finding_context(self, finding: Finding, number: int) -> Dict[str, str]:
        """Build template context for a finding."""
        # Severity badge
        severity_badges = {
            Severity.CRITICAL: "🔴 Critical",
            Severity.HIGH: "🟠 High",
            Severity.MEDIUM: "🟡 Medium",
            Severity.LOW: "🟢 Low",
            Severity.INFO: "🔵 Informational",
        }
        
        # Evidence section
        evidence_section = ""
        if finding.evidence:
            evidence_parts = [e.format_markdown() for e in finding.evidence]
            evidence_section = "\n\n".join(evidence_parts)
        else:
            evidence_section = "*No evidence attached.*"
        
        # CVE section
        cve_section = ""
        if finding.cve_ids:
            cve_list = ", ".join(finding.cve_ids)
            cve_section = f"**Related CVEs:** {cve_list}"
        
        # References
        references = ""
        if finding.references:
            references = "\n".join(f"- {ref}" for ref in finding.references)
        else:
            references = "*No references.*"
        
        return {
            "finding_number": str(number),
            "title": finding.title,
            "severity": finding.severity.value.title(),
            "severity_lower": finding.severity.value,
            "severity_badge": severity_badges.get(finding.severity, finding.severity.value),
            "cvss_score": f"{finding.cvss_score:.1f}",
            "cvss_vector": finding.cvss.generate_vector() if finding.cvss else "N/A",
            "affected_asset": finding.affected_asset or "N/A",
            "description": finding.description,
            "cve_ids": ", ".join(finding.cve_ids) if finding.cve_ids else "None",
            "cwe_ids": ", ".join(finding.cwe_ids) if finding.cwe_ids else "None",
            "cve_section": cve_section,
            "evidence_section": evidence_section,
            "remediation": finding.remediation or "No remediation guidance provided.",
            "remediation_priority": "Immediate" if finding.severity in [Severity.CRITICAL, Severity.HIGH] else "Standard",
            "references": references,
            "discovered_at": finding.discovered_at.strftime("%Y-%m-%d"),
            "reported_at": datetime.now().strftime("%Y-%m-%d"),
            "impact_analysis": self._estimate_impact(finding),
        }
    
    def _render_remediation_summary(self, report: Report) -> str:
        """Render remediation summary section."""
        if not report.findings:
            return "*No remediation required.*"
        
        lines = []
        for severity in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]:
            findings = report.get_findings_by_severity(severity)
            if findings:
                lines.append(f"### {severity.value.title()} Priority")
                for finding in findings:
                    if finding.remediation:
                        lines.append(f"- **{finding.title}**: {finding.remediation[:100]}...")
                    else:
                        lines.append(f"- **{finding.title}**: Remediation pending")
                lines.append("")
        
        return "\n".join(lines) if lines else "*No remediation guidance available.*"
    
    def _get_critical_summary(self, report: Report) -> str:
        """Get summary of critical findings for executive template."""
        critical = report.get_findings_by_severity(Severity.CRITICAL)
        high = report.get_findings_by_severity(Severity.HIGH)
        
        urgent = critical + high
        if not urgent:
            return "No critical or high severity issues requiring immediate attention."
        
        lines = []
        for finding in urgent[:5]:  # Top 5
            lines.append(f"- **{finding.title}** ({finding.severity.value.title()}): {finding.description[:100]}...")
        
        return "\n".join(lines)
    
    def _get_findings_table(self, report: Report) -> str:
        """Get findings summary table."""
        if not report.findings:
            return "*No findings.*"
        
        lines = ["| # | Finding | Severity | Asset |", "|---|---------|----------|-------|"]
        for i, finding in enumerate(report.sorted_findings, 1):
            lines.append(
                f"| {i} | {finding.title} | {finding.severity.value.title()} | {finding.affected_asset or 'N/A'} |"
            )
        
        return "\n".join(lines)
    
    def _estimate_impact(self, finding: Finding) -> str:
        """Estimate impact based on finding severity and type."""
        impacts = []
        
        if finding.cvss and finding.cvss.confidentiality == "H":
            impacts.append("- Access sensitive data")
        if finding.cvss and finding.cvss.integrity == "H":
            impacts.append("- Modify system data or configuration")
        if finding.cvss and finding.cvss.availability == "H":
            impacts.append("- Disrupt system availability")
        
        if not impacts:
            severity_impacts = {
                Severity.CRITICAL: "- Complete system compromise",
                Severity.HIGH: "- Significant data exposure or system access",
                Severity.MEDIUM: "- Limited data access or configuration issues",
                Severity.LOW: "- Minor information disclosure",
                Severity.INFO: "- Informational finding with minimal impact",
            }
            impacts.append(severity_impacts.get(finding.severity, "- Impact assessment pending"))
        
        return "\n".join(impacts)
